# Generated by Django 4.0.2 on 2022-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=30)),
                ('Course_name', models.CharField(max_length=30)),
            ],
        ),
    ]
