# Generated by Django 4.0.2 on 2022-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0002_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=30)),
                ('Assignments', models.CharField(max_length=30)),
                ('Reading_Materials', models.CharField(max_length=30)),
            ],
        ),
    ]
