# Generated by Django 4.0.2 on 2022-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0003_course_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=30)),
                ('Assignments_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterials_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=30)),
                ('ReadingMaterials_id', models.CharField(max_length=30)),
            ],
        ),
    ]
