# Generated by Django 4.0.2 on 2022-07-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0004_assignment_details_readingmaterials_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_details',
            name='Assignments_content',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='readingmaterials_details',
            name='ReadingMaterials_content',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment_details',
            name='Assignments_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment_details',
            name='Course_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='readingmaterials_details',
            name='Course_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='readingmaterials_details',
            name='ReadingMaterials_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
