# Generated by Django 4.0.2 on 2022-07-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0005_assignment_details_assignments_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_details',
            old_name='Assignments_content',
            new_name='Assignment_content',
        ),
        migrations.RenameField(
            model_name='assignment_details',
            old_name='Assignments_id',
            new_name='Assignment_id',
        ),
        migrations.RenameField(
            model_name='readingmaterials_details',
            old_name='ReadingMaterials_content',
            new_name='ReadingMaterial_content',
        ),
        migrations.RenameField(
            model_name='readingmaterials_details',
            old_name='ReadingMaterials_id',
            new_name='ReadingMaterial_id',
        ),
    ]
