# Generated by Django 4.0.2 on 2022-07-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0006_rename_assignments_content_assignment_details_assignment_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingMaterials_Details',
            new_name='ReadingMaterial_Details',
        ),
    ]
