# Generated by Django 4.0.2 on 2022-07-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0007_rename_readingmaterials_details_readingmaterial_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='static/Intern_app')),
            ],
        ),
    ]
