# Generated by Django 4.0.2 on 2022-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0010_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Ass_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=30)),
                ('Course_name', models.CharField(max_length=30)),
                ('Assignment_id', models.CharField(max_length=30)),
                ('Submission_content', models.FileField(upload_to='static/Intern_app')),
            ],
        ),
    ]
