# Generated by Django 4.0.2 on 2022-07-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_app', '0012_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
